### ISSUE TITLE
 is it possible to support the fine-tuning of the llava-next-interleave series？

### ISSUE THREAD

**Issue by qiuchen001** [zjysteven/lmms-finetune#15]
Many thanks for this interesting project and great author, would it be possible to support the fine-tuning of the llava-next-interleave series, it might be more helpful to support images and videos!

**Comment by zjysteven** [comment]
Thank you for your interest. llava-next-interleave series is indeed supported; you can see it at [README](https://github.com/zjysteven/lmms-finetune/blob/main/README.md), [supported_models.md](https://github.com/zjysteven/lmms-finetune/blob/main/docs/supported_models.md), or run `python run.py`.

**Comment by qiuchen001** [comment]
Thank you very much for responding to me. I did check the current supported model and it came up with:
![image](https://github.com/user-attachments/assets/98bcd48f-1cf3-4fb4-8f2f-0dee9b17c8f3)
From the results, it seems that the llava-next-interleave family is not currently supported.

**Comment by zjysteven** [comment]
I think `llava-interleave-xxxx` is what you want. See https://huggingface.co/llava-hf/llava-interleave-qwen-0.5b-hf


![image](https://github.com/user-attachments/assets/821ee903-2125-4f01-8626-15d8bb8c082d)

**Comment by qiuchen001** [comment]
I'm going to take a wild guess that the fine-tuning models that are shown to be supported in this project are llava-interleave-xxx, does that also mean that fine-tuning of the llava-next-interleave-xxx family is supported?

**Comment by zjysteven** [comment]
By the screenshot from huggingface model page I was saying `llava-interleave-xxxx` is exactly `llava-next-interleave` (it's just the huggingface's naming some how doesn't include `next`). But correct me if I'm wrong. If that's the case you can paste the huggingface model path of the correct model here.

**Comment by qiuchen001** [comment]
If that's the case it's fantastic, I'll try it, thank you very much!

**Comment by fedshyvana** [comment]
I think if I understand correctly:
- Both llava-interleave and llava 1.5 are based on LlavaForConditionalGeneration, which means their implementation through HF and therefore the current repo will not support anyRes.
- llava-next-video supports anyres, with an additional twist that if the input is video, it uses spatial avg pooling (stride = 2) to decrease the number of tokens per frame, whereas for images, it uses the same anyRes logic as LlavaForConditionalGeneration and llava 1.6 series. 

Ultimately I think it would be really nice if there's a unified interface for llava through HF that allows:
- freely toggle between anyres and no anyres
- freely toggle between using a vision resampler to decrease tokens vs. not (whether it's image or video frames)
- in theory we should be able to just load in any existing llava models for finetuning since the paramters are fully compatible

Unfortunately this is currently not supported by HF : )

**Comment by zjysteven** [comment]
@fedshyvana The idea definitely makes sense to me. Tagging @zucchini-nlp to see if HF might be interested to support this.

**Comment by zucchini-nlp** [comment]
Hey @fedshyvana !

Indeed  llava-interleave is same as  llava-next-interleave. We didn't add the "next" in naming because the model doesn't work with anyres, which means the architecture will be mapped to the HF-LLaVa model series.

Definitely it is a cool idea to be agnostic to particular model series and support various llava-related settings. But `transformers` is not a library for constructing your own models, rather it's a library to host current trending models Therefore making a `do-it-yourself` llava models will go against our philosophy. We currently support several llava-based models, so we expect you to load the corresponding model and checkpoint. If there are any other llava checkpoints you'd like us to support, let me know and I'll try to convert checkpoint to HF style.

Anyway, I really love the idea and if anyone is willing to host such a repo, feel free to tag me for help/guidance. AFAIK original llava-vl repo has all the toggles available, though not very well documented maybe. More than happy to help with that 😄

**Comment by zjysteven** [comment]
Closing now. Feel free to reopen if there are any other questions. @qiuchen001
