### ISSUE TITLE
how to choose num_frames when finetuning? 

### ISSUE THREAD

**Issue by TonyJiang17** [zjysteven/lmms-finetune#40]
how to choose num_frames when finetuning? 

When training say llava-next-video, is there a general rule of thumb of how to choose the num_frames? should it be dependent strictly on how many frames the model was originally trained with? or depending on the video clip length? or both. Any insights would be greatly appreciated!

**Comment by zjysteven** [comment]
To my knowledge many works just fix the number of frames (e.g., 8) regardless of the input videos. I think there is efficiency considerations behind this choice (having more frames for lengthy videos would greatly expand or even explode the context length of LLMs).

A caveat with lmms-finetune currently is that we only support fixed number of frames. This is because the video model implementations of huggingface transformers do not "unpad" video frames if you pad videos with different lengths when constructing the batch. Technically you could do padding; it's just that your model is likely to be seeing many useless padded frames during the training.
